- src/content/docs/ko/readme.mdx
- src/content/docs/ko/ready/1.mdx
- src/content/docs/ko/ready/2-pg/readme.mdx
- src/content/docs/ko/ready/3.mdx
- src/content/docs/ko/ready/readme.mdx
> 대표 문서 일부 맞춤법 및 포맷팅 수정

- .github/CODEOWNERS
애슐리께서 PR 머지 전에 본인 리뷰도 필수적으로 거쳤으면 좋겠다고 하셔서 설정하였습니다.
> CODEOWNERS 설정

- src/content/docs/ko/pg/payment-gateway/settle/mybank.mdx
원 PR: https://github.com/portone-io/developers.portone.io/pull/27
문구 수정
> 내통장 결제 특정 파라미터 추가

- src/content/docs/ko/pg/payment-gateway/undefined-2.mdx
> 엑심베이 위쳇 결제수단 삭제

- src/content/docs/ko/pg/payment-gateway/rt.mdx
- src/content/docs/ko/pg/payment-gateway/spb.mdx
신 페이팔 연동가이드중 updateLoadUIRequest()함수 첫번재 파라미터 정의 누락으로 인한 수정
> 신 페이팔 연동가이드 수정

- src/content/docs/_redir.yaml
- src/files.d.ts
- src/layouts/Docs.astro
- src/layouts/Redir.astro
- src/pages/docs/[lang]/[...slug].astro
- src/pages/docs/[lang]/index.astro
- src/pages/docs/index.astro
- src/pages/index.astro
close #53
`src/content/docs/_redir.yaml` 파일에 리디렉션 규칙을 추가할 수 있도록 하였습니다.
> 문서 리디렉션 기능

- src/content/docs/ko/result/webhook.mdx
context: https://chai-finance.slack.com/archives/C01KWKGEXLM/p1687780584881549?thread_ts=1687765389.128369&cid=C01KWKGEXLM
> 웹훅 IP 관련 문서 업데이트

- src/content/docs/ko/result/webhook.mdx
어제 @disjukr 께서 수정하다가 개수 설명 수정이 빠져서 마저 수정했습니다
> 웹훅 IP 개수 설명 두개 => 세개

- src/content/docs/ko/v2-payment/webhook.mdx
- 웹훅이 발송되는 케이스를 더 구체화하였습니다.
- IP를 이용한 웹훅 요청 검증에 관한 가이드를 추가하였습니다.
> Core V2 웹훅 가이드 개선

- src/content/docs/ko/pg/payment-gateway/paymentwall.mdx
context https://chai-finance.slack.com/archives/C03N8773P1A/p1687938579247879
> paymentwall 예시 코드 수정

- src/content/docs/ko/pg/payment-gateway/paymentwall.mdx
테스트 결제수단 활성화 파라미터 `use_test_method` 설명이 누락되어 추가하였습니다
> 페이먼트월 테스트 결제수단 설명 추가

- src/content/docs/ko/ready/2-pg/payment-gateway/undefined-1.mdx
> 페이먼트월 문구수정

- .vscode/settings.json
- prettier.config.cjs
제 환경에서 포매터가 잘 안 돌길래 잘 돌게 고쳤습니다.
> Prettier 및 VSCode 포매팅 설정 개선

- src/content/docs/ko/pg/payment-gateway/kg.mdx
context: https://chai-finance.slack.com/archives/C03N8773P1A/p1685515112046169
before:
after:
> kg 모빌리언스 결제수단 추가

- src/content/docs/ko/auth/guide/3.mdx
> @Brody-Kim sdk가 구버젼으로 되어 있어 1.3 버젼으로 수정합니다.
> 오래된 SDK 사용 가이드 최신화

- src/components/release-note/Nav.astro
- src/content/docs/ko/_nav.yaml
- src/content/docs/ko/etc/budget.mdx
- src/layouts/sidebar/LeftSidebar.astro
context: https://www.notion.so/chaifinance/fab077df452c4c80b26b1974bf0688a7
> 좌측 메뉴 구성 1차 정리

- src/content/docs/ko/pg/payment-gateway/daou/readme.mdx
> 키움페이 파라미터 수정

- src/content/docs/ko/pg/payment-gateway/paymentwall.mdx
> 페이먼트월 비인증 결제 가이드 수정

- src/content/docs/ko/api/identity-verification-api/request-otp-api.mdx
otp 요청시 YYYYMMDD 로 잘못 표기되어 있는 부분 수정
> otp 요청시 YYYYMMDD 로 잘못 표기되어 있는 부분 수정

- src/content/release-notes/api-sdk/2023-07-31.mdx
> 릴리즈노트 API/SDK 2023-07-31.mdx

- src/content/docs/ko/pg/payment-gateway/nhn-kcp.mdx
KCP 인증결제창에서 할인쿠폰 UX를 컨트롤 할수 있는 기능 안내
> kcp 할인쿠폰 컨트롤 기능 추가.mdx

- src/content/docs/ko/pg/payment-gateway/nice-v2/readme.mdx
buyer_tel 파라미터가 필수가 아님에도 필수로 기재되어 내용수정
> 신나이스페이먼트 파라미터 수정.mdx

- src/components/gitbook/Hint.astro
- src/content/docs/ko/pg/payment-gateway/nice-v2/readme.mdx
> 신나이스페이먼츠 주의사항 추가

- src/content/docs/ko/auth/guide/2.mdx
Preview: https://developers-git-docs-update-tier-code-portone.vercel.app/docs/ko/auth/guide/2
> 하위가맹점 객체 초기화에 대한 명시적 안내 추가

- src/content/docs/ko/ready/2-pg/payment-gateway/nice-v2.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/nice.mdx
> 결제취소 비밀번호 가이드 추가.mdx

- src/content/docs/ko/pg/payment-gateway/rt.mdx
> 유의사항 추가.mdx

- src/content/docs/ko/ready/2-pg/payment-gateway/undefined-1.mdx
> 페이먼트월 취소 유의사항 추가.mdx

- src/content/docs/ko/sdk/javascript-sdk/payrt.mdx
> JS SDK 응답파라미터 유의사항 수정.mdx

- src/content/docs/ko/tip/pg-2.mdx
> pg사 코드표 (신)나이스페이먼츠 코드 수정

- src/content/docs/ko/pg/payment-gateway/rt/warning.mdx
> 페이팔 RT Manges 파라미터 수정

- src/content/docs/ko/pg/payment-gateway/rt.mdx
> 페이팔 STC API 주석 수정.mdx

- src/content/docs/ko/auth/guide/5/post.mdx
기존 코드는 `getPaymentData.data`라고 되어 있지만
실제 API 응답에선 `getPaymentData.data.response`에 담겨 있음.
https://api.iamport.kr/#!/payments/getPaymentByImpUid
> `결제정보 사후 검증하기` 문서 예제코드 오류 수정

- src/content/docs/ko/auth/guide/3.mdx
https://developers.portone.io/docs/ko/auth/guide/3
여기서 "IMP 객체 초기화" 누르면 404 페이지로 넘어가는데 이 문제 때문이 맞을까요?
> fix: broken link

- src/content/docs/ko/pg/payment-gateway/rt.mdx
> STC API 주석수정.mdx

- src/content/docs/ko/platform/api.mdx
> switched base url error

- src/content/docs/ko/tip/pg-2.mdx
https://chai-finance.slack.com/archives/C03N8773P1A/p1692778184949959?thread_ts=1692772017.937969&cid=C03N8773P1A
> PG사 코드표 퀵페이 중복 제거

- src/content/docs/ko/_nav.yaml
- src/content/docs/ko/pg/payment-gateway/spb/stc.mdx
(신)페이팔 고위험 거래(STC) 산업군 별 파라미터를 추가한 PR입니다.
> (신)페이팔 고위험 거래(STC) 산업군 별 파라미터 추가

- src/content/docs/ko/pg/payment-gateway/danal.mdx
> 다날 휴대폰 결제 부가기능 추가

- src/content/docs/ko/pg/payment-gateway/newtoss/readme.mdx
오기입된 내용.
context: https://chai-finance.slack.com/archives/C01FJSM3XC5/p1693361570655419?thread_ts=1693359154.872539&cid=C01FJSM3XC5
> 신토스 - 특정 카드사 노출 내용 제거

- .gitignore
- astro.config.ts
- package.json
- pnpm-lock.yaml
- src/content/docs/en/ready/2-pg/payment-gateway-settings/undefined-2.mdx
- src/content/docs/en/sdk/javascript-sdk/rps.mdx
- src/content/docs/ko/wordpress/wordpress/button.mdx
- src/pages/api/rest-v1/[...slug].astro
- src/pages/api/rest-v1/_Page.tsx
- src/pages/api/rest-v2/[...slug].astro
- src/pages/api/rest-v2/_Page.tsx
- tsconfig.json
REST API 페이지에서 perma link를 구현하기 위함
> Vercel adapter로 SSR 가능하도록 함

- src/content/docs/ko/api/cash-receipt-api/issue-cash-receipt-api.mdx
안녕하세요! 문서를 읽어보던 중에 오타가 보여서 수정했습니다.
확인 부탁드려요 :D
> refactor: 게좌 오타 수정

- src/content/docs/ko/readme/get-started.mdx
> 소개문구 수정.mdx

- src/content/docs/ko/auth/guide/readme.mdx
> 인증결제동영상가이드추가.mdx

- src/content/docs/ko/v2-payment/readme.mdx
> 인증결제동영상가이드추가-v2.mdx

- src/content/docs/ko/sdk/javascript-sdk/payrq.mdx
> 삼성페이결제수단 코드 오류 수정.mdx

- src/content/docs/ko/ready/2-pg/payment-gateway/blue.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/danal.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/exim.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/jtnet.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/kg-1.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/kg.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/kicc.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/ksnet.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/nhn-kcp.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/nice-v2.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/nice.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/paypal-spb.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/paypal.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/smartro-v2.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/tosspayments.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/undefined-1.mdx
- src/content/docs/ko/ready/2-pg/payment-gateway/undefined-2.mdx
- src/content/docs/ko/ready/2-pg/pg/alipay.mdx
- src/content/docs/ko/ready/2-pg/pg/kakao.mdx
- src/content/docs/ko/ready/2-pg/pg/naverpay-order.mdx
- src/content/docs/ko/ready/2-pg/pg/payco.mdx
- src/content/docs/ko/ready/2-pg/pg/toss-brandpay.mdx
- src/content/docs/ko/ready/2-pg/pg/toss.mdx
- src/content/docs/ko/ready/2-pg/pg/undefined.mdx
> Change menu naming

- src/content/docs/ko/_nav.yaml
context: https://chai-finance.slack.com/archives/C03N8773P1A/p1695006066677789
> jtnet 문서 메뉴에서 제거

- src/content/docs/ko/pg/simple/kakopay.mdx
context: https://chai-finance.slack.com/archives/C03N8773P1A/p1695107770809799
> 카카오페이 결제연동 관련 참고사항 추가

- src/content/docs/ko/result/webhook.mdx
> 웹훅 notice url 설명 추가

- src/content/docs/ko/pg/payment-gateway/undefined-2.mdx
context: https://chai-finance.slack.com/archives/C03N8773P1A/p1695088633164299
> 엑심베이 sdk 문서에 간편결제수단 내용 추가

- src/content/docs/ko/auth/guide-1/bill/readme.mdx
context: https://chai-finance.slack.com/archives/C028YPU38F2/p1696475750772099
> 빌링키 결제 연동 문서에서 pg사 목록에 웰컴페이먼츠 추가

- src/content/docs/en/_nav.yaml
context: https://chai-finance.slack.com/archives/C03N8773P1A/p1697077102831429
> 영문문서 좌측 메뉴에서 차이페이 관련 메뉴 제거

- src/content/docs/ko/auth/guide-1/bill/readme.mdx
context: https://chai-finance.slack.com/archives/C03N8773P1A/p1697507353994669
> 비인증결제를 지원하는 PG사 목록 수정

- src/content/docs/ko/v2-payment/v2-sdk/payment-request.mdx
* fixedMonth의 타입이 잘못 명시돼 있어 수정했습니다.
* availableCards 파라미터에 대한 내용이 빠져있어서 추가했습니다.
* validHours, dueDate 파라미터 타입 수정
> docs: V2 SDK 결제 요청파라미터 잘못된 항목 & 빠진 내용 추가

- src/content/docs/ko/v2-payment/v2-sdk/payment-request.mdx
context: https://chai-finance.slack.com/archives/C02KQFUB8GG/p1698209796953799
> 잘못된 V2 SDK 결제 요청 파라미터 설명 수정

- src/content/docs/ko/v2-payment/v2-sdk/payment-request.mdx
context: https://chai-finance.slack.com/archives/C03N8773P1A/p1698215219603109
> v2 core 지원 목록만 보이도록 수정

- src/state/nav.ts
> url에 버전토글 정보 포함시킴

- src/content/docs/ko/pg/payment-gateway/undefined-2.mdx
context: https://chai-finance.slack.com/archives/C03N8773P1A/p1699516458136209
dcc 통화 목록이 포함되도록 수정하였습니다.
엑심베이 통화코드 관련 문서: https://developer.eximbay.com/api_sdk/code-etc.html
> 엑심베이 결제통화코드 목록 업데이트

- src/content/docs/ko/sdk/javascript-sdk/payrq.mdx
context: https://chai-finance.slack.com/archives/C03N8773P1A/p1699840067258289
> sdk 요청 파라미터 pg 필드 설명 수정

- src/layouts/LayoutBase.astro
- src/layouts/TrackingScript.astro
- src/pages/api/rest-v2-legacy/[...slug].astro
- src/pages/api/rest-v2-legacy/index.astro
- src/pages/platform/[...slug].astro
https://developers-git-v2-api-legacy-portone.vercel.app/api/rest-v2-legacy
> V2 기존 문서 별도페이지로 분리

- src/content/docs/ko/result/webhook.mdx
[페이지 링크](https://developers.portone.io/docs/ko/result/webhook?v=v1)
Before:
After:
> fix: 웹훅 예제코드 포매팅 수정

- src/content/docs/ko/pg/payment-gateway/nice.mdx
> (구) 나이스 paymethod 수정

- src/content/docs/ko/pg/simple/toss-brandpay/module.mdx
- src/content/docs/ko/sdk/javascript-sdk/load-module.mdx
loadModule의 파라미터를 넘기는 방식이 잘못 작성돼 있어 수정했습니다.
또한 loadModule이 비동기 함수라는 점을 확실하게 표현하기 위해 loadModule 예시 앞에 await를 붙여 주었습니다.
> docs: loadModule 잘못된 내용 수정

- src/layouts/rest-api/category/Expand.tsx
- src/layouts/rest-api/category/index.tsx
- src/layouts/rest-api/category/type-def.tsx
> api 문서 접기 펼치기 버튼 이해하기 쉽게 수정

- src/schema/v1.openapi.json
TODO 
-  [x] (신) 토스페이 배포 후 [prod](https://api.iamport.kr/api/docs)의 openapi json 내용으로 갱신
> (신) 토스페이 관련 v1 openapi 갱신

- src/content/docs/ko/result/webhook.mdx
> fix: 오타 수정

- src/content/docs/ko/v2-payment/webhook.mdx
V2 웹훅 문서에 적혀있는 status가 실제 발송값과 달라서 수정한 PR입니다.
> fix: 웹훅 status를 실제 발송되는 값으로 수정

- src/schema/v2.openapi.json
Public API Service 가 핫픽스로 1.6.3 버전이 배포되면서 변경된 스키마를 업데이트합니다.
> V2 Open API 1.6.3 hotfix schema update

- src/content/docs/ko/auth/guide/5/post.mdx
이전 버전의 API 명세 URL로 연동되어 있던 것을 새로운 API Docs URL로 수정
> Modify: 하이퍼링크가 URL 최신화

- src/schema/v2.openapi.json
Public API 1.6.4 정기배포가 완료되어 스키마를 업데이트합니다.
> V2 Public API Schema update - 1.6.4

- src/content/docs/ko/auth/guide/3.mdx
context: https://chai-finance.slack.com/archives/C067FEWAMAQ/p1703223510486959
> 결제 요청하기 페이지에서 codepen 예제 제거

- src/layouts/rest-api/category/type-def.tsx
context: https://chai-finance.slack.com/archives/C03N8773P1A/p1704180950354889
| Before | After |
| --- | --- |
| <img width="597" alt="image" src="https://github.com/portone-io/developers.portone.io/assets/690661/7737e95d-0235-497b-aed0-beb42424c5b6"> | <img width="598" alt="image" src="https://github.com/portone-io/developers.portone.io/assets/690661/46228590-5cb4-4632-81dd-b1ee89e22504"> |
> api 문서에서 필드 설명 보여주는 로직 수정

- scripts/download-schema.ts
- scripts/render-v1.ts
- src/schema/v2.openapi.json
- 조금 더 코드 재사용성 있게 만듦
- 서버 목록에서 내부용 주소 걸러냄
> 스키마 다운로드 스크립트 정비

- src/layouts/rest-api/category/type-def.tsx
| before | after |
| --- | --- |
| ![image](https://github.com/portone-io/developers.portone.io/assets/690661/a8fab162-ed31-4496-97ee-8204e2871479) | ![image](https://github.com/portone-io/developers.portone.io/assets/690661/64b51377-33f3-43c1-b493-6097394ddd2e) |
> union type의 discriminator select ui를 필드 설명으로 밀어넣음

- src/content/docs/ko/etc/all/3.mdx
context: https://chai-finance.slack.com/archives/C021YGZEGS2/p1705039263628129
> KG이니시스 통합인증서비스 연동가이드 수정

- src/schema/v2.openapi.json
V2 Public API Service 1.7.0 이 배포되어 관련 업데이트를 개발자센터에 반영합니다.
> v2 public api service release: v1.7.0

- src/layouts/rest-api/editor/MonacoEditor.tsx
- src/layouts/rest-api/editor/RequestJsonEditor.tsx
- src/layouts/rest-api/editor/misc/install-monaco-worker.ts
- src/layouts/rest-api/endpoint/playground/Card.tsx
- src/layouts/rest-api/endpoint/playground/try/Req.tsx
> api 문서 try 영역 필드 자동완성 기능

- src/schema/v2.openapi.json
> V2 B2b Schema Update

- src/content/docs/ko/v2-payment/pg/nice-v2.mdx
> 나이스페이먼츠 설정 상대경로 주소 수정

- src/content/docs/ko/v2-payment/pg/nice-v2.mdx
birthOrNusinessRegistrationNumber -> birthOrBusinessRegistrationNumber
오타 N을 B로 수정
> docs: 나이스페이먼츠 오타 업데이트

- src/content/docs/ko/v2-payment/identity-verification.mdx
> docs:  identity-verification.mdx

- src/schema/v2.openapi.json
V2 Public API 1.12.0 릴리즈 반영입니다.
> v2 public api service release - 1.12.0

- src/content/docs/ko/tip/pg-2.mdx
PG 사 코드 페이지에 이니시스 통합인증 코드가 누락되어 있어서 추가했습니다.
> docs: pg사 코드 추가

- src/schema/v1.openapi.json
금일 [api-iamport 정기배포로](https://github.com/portone-io/api-iamport/pull/691) swagger에 추가 필드가 생겨 v1.openapi.json를 업데이트하였습니다.
> docs: v1 openapi.json 업데이트

- src/content/blog/2024-03/tgs.mdx
> fix: 기술블로그 Typed Error 예시코드 변경

- src/content/docs/ko/v2-payment/pg/paypal-v2.mdx
빌링키 발급 파라미터에 billingKey가 필요 없는데 내용에 포함되어 있어 삭제한 PR입니다.
> 페이팔 v2 문서 예제코드 잘못된 내용 수정

- src/components/gitbook/VersionGate.tsx
- src/content/docs/ko/_nav.yaml
- src/content/docs/ko/result/notice.mdx
V2 문서 내비게이션에도 가상계좌 입금통보 문서를 포함합니다.
V1 문서를 그대로 가져다 쓰는 것으로 일단 핫픽스를 했고, V1과 V2 문서를 분리해서 관리하는 공수가 괜찮으면 분리하려고 합니다.
> V2 내비게이션에 가상계좌 입금통보 포함

- src/schema/v2.openapi.json
GetB2bAccountHolder API의 에러가 잘 못 매핑돼 있던 문제를 해결한 PR입니다.
> fix: GetB2bAccountHolder 에러매핑 수정

- src/schema/v2.openapi.json
이니시스 V2에서 PAS에 신규로 추가된 에스크로 수정, 영수증 내 하위 상점 거래 등록 API를 추가 했습니다.
> 에스크로 수정, 영수증 내 하위 상점 거래 등록 API 추가

- src/content/docs/ko/pg/simple/tosspay-v2/readme.mdx
- 예제 코드 문법 오류 수정
- 잘못된 마크다운 링크 수정
> 토스페이 간편결제 링크, 린트 수정

- src/content/docs/ko/pg/payment-gateway/eximbay.mdx
엑심베이 설명에 필수 파라미터가 누락되어 있어서 추가했습니다.
> fix : 엑심베이 필수 파라미터 추가

- patches/@shikijs__rehype@1.2.1.patch
- patches/eslint-plugin-markdown@3.0.1.patch
- patches/eslint-plugin-mdx@3.1.5.patch
- patches/eslint-plugin-prettier@5.1.3.patch
- patches/remark-lint-table-cell-padding@4.1.3.patch
- pnpm-lock.yaml
*TBD*
주의: 이거 하면 patch들 해시가 바뀌어서, 머지하기 전에 `pnpm i` 한번 해서 pnpm.lock 파일 고쳐야함
> patches: Properly document Ad-Hoc patches

- src/schema/v2.openapi.json
> docs: v2 openapi 스키마 업데이트

- src/content/docs/ko/pg/payment-gateway/welcome/readme.mdx
현재 Internal server error가 발생하고 있습니다.
https://developers.portone.io/docs/ko/pg/payment-gateway/welcome/readme?v=v1
> 웰컴페이먼츠 연동 문서 누락된 import 수정

- src/content/docs/ko/v2-payment/pg/inicis-v2.mdx
이니시스 연동가이드에 작성된 API 주요 파라미터 정보를 보충합니다.
- 주요 필드 추가 (면세금액)
- required, optional 마크 오기입된 부분 수정
> 이니시스 연동가이드 일부 필드 정보 수정

- src/components/blog/PostList/PostListLayout.astro
- src/pages/blog/posts/[...slug].astro
| before | after |
| --- | --- |
| ![before](https://github.com/portone-io/developers.portone.io/assets/690661/031bbae8-2547-41bf-a36a-60469f53f019) | ![after](https://github.com/portone-io/developers.portone.io/assets/690661/4c44a00b-e885-4dac-b26e-164ab14a2646) |
> 블로그 스크롤 끝까지 내렸을 때 바닥 여백이 없어서 불편한 문제 수정

- src/content/docs/ko/_nav.yaml
- `_nav.yaml` 파일에 오타가 있어 (Unknown page) 로 표시되는 오류를 수정했습니다.
> Unkonwn page 오류 수정

- pnpm-lock.yaml
- src/schema/v2.openapi.json
PAS main 최신 기준으로 api 문서를 업데이트합니다.
> V2 API 문서 최신화

- src/content/docs/ko/auth/guide-2/refund.mdx
> Docs: 오타 수정

- src/content/docs/en/payment-integration-by-pg/payment-gateways/inicis.mdx
- src/content/docs/ko/pg/payment-gateway/inicis.mdx
'example://'이 아닌 'example'로 요청하는 경우가 있어서, 설명에 '://'를 추가했습니다.
Reference:
- https://portone-io.slack.com/archives/C067FEWAMAQ/p1716538048060129?thread_ts=1715563774.600649&cid=C067FEWAMAQ
> payment-gateway/inicis.mdx: app_scheme 예제 수정

- src/content/docs/ko/pg/payment-gateway/blue.mdx
> 블루월넛 문서 복구

- src/layouts/sidebar/DocsNavMenu.astro
- src/layouts/sidebar/DropdownLink.tsx
- uno.config.ts
> 개발자문서 모바일 링크 구현

- src/schema/v2.graphql
- src/schema/v2.openapi.json
[플랫폼 핫픽스](https://www.notion.so/chaifinance/2024-06-05-platform-be5e7b6446ac4e73b64aee39193c84bf?utm_content=be5e7b64-46ac-4e73-b64a-ee39193c84bf&utm_campaign=TRHRYMUV7&pvs=6)관련 API 문서를 업데이트 합니다. 릴리즈 노트 추후 추가 예정
송금대행 릴리즈 때 graphql 스키마 업데이트를 안해서 diff가 큽니다
> V2 플랫폼 파트너 API 업데이트

- src/content/docs/ko/pg/payment-gateway/eximbay.mdx
- src/content/docs/ko/pg/simple/payco.mdx
> 페이코 popup 파라미터 설명 추가

- src/layouts/rest-api/schema-utils/operation.ts
일단 안 보이는 원인은 찾았습니다.. 😅 원래 의도는 Union Tag가 아니라 다른 방식으로 표시되게 하려는 것 같았는데, 이를 그냥 Union Tag로 처리할지 아니면 다른 방식으로 표시되게 할지 고민되네요.
> 에러 type 값 표시 누락 수정

- src/content/docs/ko/v2-payment/identity-verification.mdx
channelKey 주석을 처음보는 사람도 잘 이해할 수 있도록 수정
> imporve: v2 본인인증 연동 문서 개선

- src/content/docs/ko/auth/guide-1/readme.mdx
- src/content/docs/ko/authpay/guide.mdx
V1도 에러 응답 JSON으로 내려온다고 하여 여기도 반영했습니다.
> 샘플 코드에서 에러 본문을 출력하도록 변경 (V1까지)

- src/layouts/rest-api/index.tsx
ref: https://portone-io.slack.com/archives/C03N8773P1A/p1718608700086539
> API 문서에서 해시를 포함한 URL로 접속했을 때에도 종종 해당 섹션으로 스크롤이 이뤄지지 않던 문제 수정

- src/content/docs/ko/pg/payment-gateway/nice-v2/readme.mdx
- src/content/docs/ko/v2-payment/pg/nice-v2.mdx
> 신나이스페이먼츠 유의사항 추가

- src/content/docs/ko/v2-payment/webhook.mdx
뭔가 최신화가 안 되어 있을 줄 알고 들어갔는데 잘 되어 있어서 express에서 next(err) 해줘야 하는 것만 수정했습니다
> style: 웹훅 샘플 코드 약간 수정

- src/schema/v2.graphql
- src/schema/v2.openapi.json
> 플랫폼 서비스 api 문서 최신화

- src/content/docs/ko/v2-payment/pg/smartro-v2.mdx
> (신) 스마트로 필수 파라미터 수정

- src/content/docs/ko/pg/simple/naver.mdx
네이버페이 유의사항 수정 및 빌링키 삭제 API 유의사항 추가
> 네이버페이 유의사항 수정 및 빌링키 삭제 API 유의사항 추가

- src/schema/v1.openapi.json
- promotion_id 설명 추가
- 오타 수정
- 비인증 결제 onetime 에서 birth 파라미터가 옵셔널로 변경
- 해피머니 결제 수단 삭제
> v1.openapi.json: 문서 최신화

- src/schema/v2.graphql
- src/schema/v2.openapi.json
https://portone-io.slack.com/archives/C06JQAD295Y/p1724295342176799
`main` 브랜치에 누락된 스키마 변경사항이 있어서 `main` 브랜치가 아닌 `fix/hide-inicis-03` 브랜치를 기준으로 스키마를 업데이트 했습니다.
> V2 스키마 업데이트

- src/misc/contentIndex.ts
- 기존 docs 기준으로 content-index가 생성되어 검색 시에 오류가 발생하는 현상을 수정했습니다.
> contentIndex 수정

- scripts/calc-api-redir.ts
- scripts/download-schema.ts
- scripts/nav-labels.ts
deno 스크립트 의존성을 JSR 바탕으로 일괄적으로 업데이트합니다. download-schema 제외하고는 동작 테스트를 해보지는 않았는데(실행은 됨) 일단 올리고 깨지면 고치려 합니다
> feat: update scripts to jsr

- src/routes/(root)/docs/ko/etc/sdk.mdx
> 네이티브 sdk 설명 추가

- src/layouts/rest-api/schema-utils/operation.ts
- src/layouts/rest-api/schema-utils/type-def.ts
> API 문서 additionalProperties 지원

- src/routes/(root)/release-notes/(note)/api-sdk/2024-09-27.mdx
> 릴리즈노트 날짜 수정

- src/routes/(root)/opi/ko/_nav.yaml
- src/routes/(root)/opi/ko/support/contact.mdx
* 사이드바 `기술지원` 메뉴에 `직접 문의하기` 를 추가했습니다.
* 해당 페이지에 v1, v2 각각의 기술지원 메일을 간략히 명시했습니다.
> 기술지원 메일 명시

- src/routes/(root)/opi/ko/integration/pg/v1/rt/readme.mdx
- src/routes/(root)/opi/ko/integration/pg/v1/rt/warning.mdx
- src/routes/(root)/opi/ko/integration/pg/v2/paypal-v2.mdx
오타 수정합니다.
`manges` => `magnes`
TODO: 이미지 내 오타 수정 및 파일명 변경필요
> [chore]paypal v2 가이드 오타 수정

- src/schema/v2.graphql
- src/schema/v2.openapi.json
PAS main 브랜치 기준으로 v2 api schema를 업데이트했습니다.
> V2 API Schema 업데이트

- src/layouts/rest-api/schema-utils/category.ts
- src/schema/v2.openapi.json
[요약]
PAS 정기배포(9)가 운영환경에 배포되어 스키마 변경사항을 반영합니다.
추가로 이번에 B2B API Category가 invisible 처리되었으나 코드에 이 부분을 처리하는 로직이 없어서 신규로 구현했습니다.
> 정기배포 스키마 업데이트 (Weekly-9) & API Category invisible 태그 적용

- src/routes/(root)/sdk/ko/v2-server-sdk/readme.mdx
- 언어별 의존성 추가 방법을 추가하고, 탭으로 그룹화했습니다.
- "레포지토리"를 "저장소"로 변경했습니다.
- 소제목 "JavaScript 및 TypeScript"를 "JavaScript"로 변경했습니다.
> 서버 SDK 소개 개선

- src/layouts/rest-api/editor/JsonViewer.tsx
- src/layouts/rest-api/editor/MonacoEditor.tsx
- src/layouts/rest-api/endpoint/playground/try/Req.tsx
- src/layouts/rest-api/endpoint/playground/try/ReqSample.tsx
- src/layouts/rest-api/endpoint/playground/try/Res.tsx
- Response 결과가 업데이트 되지 않는 오류 수정
- Request Sample 에서 query 파라미터에 불필요한 quote가 붙는 오류 수정
> API Try 기능 오류 수정

- src/routes/(root)/opi/ko/integration/webhook/readme-v2.mdx
서버 SDK에 웹훅 스키마를 추가하면서 웹훅 검증 코드를 일부 수정했습니다.
> 웹훅 검증 코드 최신화

- src/layouts/sidebar/search.tsx
- 텍스트 크기 14px -> 12px로 변경
- Ctrl, K 간 간격 2px -> 4px로 변경
> Ctrl K를 이쁘게 만들기

- src/routes/(root)/opi/ko/integration/start/v2/checkout.mdx
- src/routes/(root)/sdk/ko/readme/index.mdx
결제연동 시작하기 및 v2 SDK 소개 문서에 샘플 프로젝트 링크를 추가합니다.
> 샘플 프로젝트 링크 추가

- src/routes/(root)/opi/ko/integration/webhook/readme-v2.mdx
현재 cancellationId를 내려주고 있는데 문서에 반영되어 있지 않습니다.
> Transaction.CancelPending 웹훅 이벤트에 cancellationId 추가

- src/layouts/rest-api/endpoint/playground/try/Req.tsx
> Request Sample에서 HTTP method를 대문자로 설정

- src/components/interactive-docs/LanguageSelect.tsx
- src/components/interactive-docs/index.tsx
- src/state/interactive-docs/index.tsx
> 퀵 가이드 상태 정리

- src/components/interactive-docs/CodePreview.tsx
- src/layouts/docs/InteractiveDocs.tsx
- src/routes/(root)/opi/ko/quick-guide/payment/_preview/Preview.tsx
[Figma 링크](https://www.figma.com/design/KiWuigpgk9vyGdoI4Rz5Y8/Dev-Center?node-id=3404-8693&t=5BZAAflrfC0Uaovf-4)
> 프리뷰에 미리보기 표기 추가 & Select 컴포넌트 문구 수정

- src/layouts/trackers/Trackers.tsx
- src/routes/(root)/blog/(list).tsx
- src/routes/(root)/blog/(list)/tags/[tag].tsx
- Vercel 설정 프리셋을 Astro 에서 solid-start(v1) 으로 변경했습니다.
- 기존 Vercel 환경변수에 `VITE_` 접두사를 추가했습니다.
> GoogleTabManager 수정

- packages/remark-param-tree/src/index.ts
related #722
- required 조건이 반대로 설정되어 있는 부분 수정
> 파라미터 required 조건 수정

- src/routes/(root)/opi/ko/quick-guide/payment/_preview/backend/express/server.js.ts
PortOneClient(secret) -> PortOneClient({ secret: secret }) 으로 변경합니다.
> 퀵 가이드 express 예제 오타 수정

- src/routes/(root)/opi/ko/extra/promotion/integration.mdx
파라미터 설명 내 "프모로션" 오타를 "프로모션"으로 변경합니다.
> 프모로션 => 프로모션

- src/routes/(root)/opi/ko/quick-guide/payment/_preview/frontend/html/index.html.ts
> 퀵 가이드 HTML 프리뷰 오타 수정

- src/schema/v2.graphql
- src/schema/v2.openapi.json
현 PAS main 기준으로 api 문서를 최신화합니다.
> api 문서 최신화

- src/routes/(root)/opi/ko/integration/webhook/readme-v2.mdx
- src/routes/(root)/opi/ko/quick-guide/payment/_preview/backend/express/server.js.ts
> 서버 SDK getPayment 파라미터 수정

- packages/browser-sdk-mdx-codegen/src/index.ts
- packages/browser-sdk-mdx-codegen/src/parameter.ts
- packages/browser-sdk-mdx-codegen/src/schema.ts
- packages/remark-param-tree/src/transform/typeDef.ts
- src/components/parameter/Parameter.tsx
- src/components/parameter/ParameterDeclaration.tsx
- src/components/parameter/SDKParameter.tsx
- src/schema/browser-sdk.yml
- `emptyObject`: `object` -> `{}`
- `unknown`:  `any` -> `json`
- 컴포넌트가 중복으로 들어가지 않도록 마크업 구조 개선
- SDK 스키마 업데이트
- Parameter.Details 컴포넌트 최적화
> SDK 파라미터 수정 & 스키마 업데이트

- src/routes/(root)/opi/ko/support/_components/tls-support/java6-java-security-edit.tsx
> TLS 가이드 Java 6 코드 개행

- scripts/download-schema.ts
- src/schema/v2.openapi.json
> 본인인증 & 현금영수증 API 추가

- src/layouts/rest-api/nav-menu/NavMenu.tsx
- src/layouts/sidebar/DocsNavMenu.tsx
- src/layouts/sidebar/DropdownLink.tsx
- 추가로 v2 REST API가 아닌, 현재 버전에 맞는 REST API 문서로 이동하도록 수정
> REST API 문서에도 LeftSidebar에 드롭다운 페이지 이동 추가

- src/layouts/rest-api/category/type-def.tsx
> ReqPropertiesDoc 스타일 수정

- src/schema/v2.openapi.json
신규 API인 사업자등록 정보조회의 카테고리를 `B2B API`에서 `파트너 정산 관련 API` 하위로 이동시킵니다.
> B2B 사업자등록 정보조회 API 카테고리 변경

- scripts/mdx-to-markdown/jsx/condition.test.ts
- scripts/mdx-to-markdown/jsx/condition.ts
- scripts/mdx-to-markdown/jsx/index.test.ts
- scripts/mdx-to-markdown/jsx/index.ts
- scripts/mdx-to-markdown/mdx-parser.ts
MDX 내 `<Condition ...>` 태그가 마크다운 변환 상 무시되지 않고 html component 형태로 변환되도록 개선합니다.
> `<Condition ...>` JSX 태그에 대한 마크다운 변환 추가

- src/components/Metadata.tsx
- src/routes/(root).tsx
- src/routes/(root)/opi/ko/quick-guide/payment/index.mdx
- canonical 링크에 버전 표기 추가
- 불필요한 canonical 링크 제거
> canonical 링크에 버전 표기 추가

- src/components/interactive-docs/CodePanel.tsx
- src/components/interactive-docs/PayMethodSelect.tsx
- src/components/interactive-docs/PgSelect.tsx
- uno.config.ts
- CodePanel: left-sidebar
- PayMethodSelect, PgSelect: dropdown-link
> 퀵 가이드 z-index 문제 해결

- src/routes/(root)/opi/ko/integration/pg/v2/danal-identity-verification.mdx
- src/routes/(root)/opi/ko/integration/pg/v2/tosspayments.mdx
- src/routes/(root)/opi/ko/quick-guide/payment/index.mdx
- src/schema/browser-sdk.yml
> V2 토스페이먼츠 카드결제 및 다날 본인인증 수정

- src/schema/browser-sdk.schema.json
- src/schema/browser-sdk.yml
> browser-sdk JSON 스키마 추가

- src/schema/browser-sdk.yml
- https://github.com/portone-io/browser-sdk-generator/pull/2
- #849
> 브라우저 SDK 스키마 업데이트

- src/routes/(root)/opi/ko/_nav.yaml
- src/routes/(root)/opi/ko/integration/pg/v2/welcome.mdx
웰컴페이먼츠 V2 문서를 추가합니다.
파라미터 설명은 곧 #859 로 대체될 예정입니다.
> feat: add welcome v2 docs

- src/components/interactive-docs/index.tsx
https://portone-io.slack.com/archives/C07UW0JF7HR/p1745424325600529
> 퀵가이드 Section active 상태일 때 배경색 변경

- src/routes/(root)/opi/ko/integration/virtual-account/readme.mdx
tosspaysments -> tosspayments 로 코드값의 오탈자를 수정했습니다.
> :pencil2: docs(webhook): Toss Payments 코드 오탈자 수정

- src/routes/(root)/opi/ko/extra/plugins/shopify/readme-v1.mdx
> 쇼피파이지원결제수단목록수정.mdx

- src/routes/(root)/opi/ko/integration/pg/v1/nhn-kcp.mdx
관련 스레드 : https://portone-io.slack.com/archives/C034ADZQMEX/p1749548885264499?thread_ts=1749532802.698079&cid=C034ADZQMEX
> v1 kcp 휴대폰결제시 필수파라미터 안내 추가

- src/routes/(root)/opi/ko/integration/pg/v1/naver.mdx
- src/routes/(root)/opi/ko/integration/ready/readme.mdx
- 채널 등록 시 chainId를 필수 입력해야하므로 신규 연동 시 naverpayChainId를 입력하지 않아도 됩니다.
> docs: naverpayChainId 파라미터 제거

- src/routes/(root)/api/rest-v2/[...slug].tsx
- src/routes/(root)/opi/ko/integration/pg/v1/nhn-kcp.mdx
> feat: document idempotency key

- src/routes/(root)/opi/ko/integration/pg/v2/eximbay-v2.mdx
- src/schema/browser-sdk.yml
> 엑심베이 products 설명 수정

- src/routes/(root)/opi/ko/integration/pg/v1/daou/readme.mdx
v1 키움페이 연동문서에 bypass.daou.DIRECT_YN 파라미터 설명을 추가했습니다.
250911 배포 예정
> docs: v1: 키움페이 bypass.daou.DIRECT_YN 파라미터 설명 추가

- src/routes/(root)/opi/ko/integration/pg/v1/inicis.mdx
v1 이니시스 연동 가이드에서 에스크로 상태변화 웹훅 기능에 대한 안내를 추가합니다.
> docs:v1 이니시스 에스크로 웹훅 기능 설명 추가
