src/content/docs/ko/pg/payment-gateway/smartro-v2/readme.mdx

스마트로 신모듈 SDK 일반 결제, 빌링키 발급 연동 가이드를 작성한 pr입니다.
[가이드초안 ](https://www.notion.so/chaifinance/Smartro-cdc5cb7918b2424f8d88f8142d6fad60?pvs=4#70757eef22584e32ac8680f804e37e98)
여기에서 확인할 수 있습니다: https://developers-git-smartro-v2-sdk-portone.vercel.app/docs/ko/pg/payment-gateway/smartro-v2/readme

스마트로 신모듈 일반결제, 빌링키 발급 연동 가이드 업데이트

---

src/content/docs/ko/ready/2-pg/pg/payco.mdx

페이코에서 정기결제 또한 지원하지만, 제목 태그에 인증결제라고만 나와 있어 코멘트를 "일반결제 및 정기결제"로 변경하였습니다

페이코 채널 연동 문서에 정기결제 표시 추가

---

src/content/docs/ko/pg/payment-gateway/toss.mdx

토스 구모듈 허브형 지원하게 됨에 따라 하단에 outdated된 허브형을 지원하지 않는 다는 문구를 삭제

토스 구모듈 허브형지원 이후 outdated된 내용 삭제

---

src/content/docs/ko/api-v2/channel.mdx

토스만 아래에 빠져나와있어서 다른 PG사처럼 탭으로 변경함

V2 채널 불러오기 API 문서 탭 정리

---

src/content/docs/ko/pg/payment-gateway/settle/readme.mdx

기존에 헥토파이낸셜은 결제와 동시에 빌링키 발급만 가능했으나 빌링키만 단독으로 발급하는 API를 신규 연동함에 따라 이에 대한 내용을 추가 및 수정한 PR 입니다. ( v1 연동에만 해당됩니다. )

docs: 헥토파이낸셜 빌링키 발급 API 추가로 인한 문서 업데이트

---

src/content/docs/ko/pg/payment-gateway/rt.mdx

- 페이팔 RT 유의사항 텍스트 링크가 잘못 걸려 있어 수정한 PR입니다.

페이팔 RT 링크가 잘못 연결된 텍스트 수정

---

vercel.json

mime sniff 취약점 방지를 위해 vercel 헤더설정에 `X-Content-Type-Options: nosniff` 를 추가합니다.
context: https://chai-finance.slack.com/archives/C02MEQHGG4E/p1693544481944109

`X-Content-Type-Options: nosniff` 헤더 추가

---

src/content/docs/en/api/subscription-payment-api/schedule-payment-api.mdx
src/content/docs/ko/api/subscription-payment-api/schedule-payment-api.mdx

[정기결제 현황에 보이지 않는다](https://chai-finance.slack.com/archives/C021YGZEGS2/p1693969477110569)는 이슈가 들어와서 확인해 보니 `schedule_at`을 밀리세컨드로 요청해서 시간 변환이 잘못되어 예약이 정상적으로 이뤄지지 않은 것으로 확인됐습니다. 
```log
php > print_r(date('Y-m-d H:i:s', 1757385657224));
57659-05-03 03:33:44
php > print_r(date('Y-m-d H:i:s', 1757385657));
2025-09-09 11:40:57
```
예제에는 unix timestamp가 초 단위의 unix 타임스탬프로 나와 있지만, 사양에 세컨드인지 밀리세컨드인지 명시되어 있지 않아서, 세컨드임을 명시했습니다.
- api-iamport 스웨거 수정: https://github.com/iamport/api-iamport/pull/595

docs: `POST /subscribe/payments/schedule`의 `schedule_at`이 세컨드임을 명시

---

src/content/docs/ko/v2-payment/identity-verification/4.mdx

본인인증 연동 문서에서 access_token -> accessToken 으로 오타를 수정합니다.
참조)
아래 PR에서 수정된 부분이며, 잘못 수정된 부분이 있어서 빠르게 해당 부분만 수정한 PR을 다시 생성하였으며 아래 PR은 Close 예정입니다. 
https://github.com/portone-io/developers.portone.io/pull/202

본인인증 문서 오타 수정

---

src/content/docs/en/payment-integration-by-pg/payment-gateways/nhh-kcp.mdx
src/content/docs/ko/pg/payment-gateway/nhn-kcp.mdx

KCP 다이렉트 경우 카드사 포인트 사용시 `카드사 포인트할부`라는 값을 `할부 개월수`에 더해서 요청을 해야 해서, 해당 내용을 문서에 추가했습니다. 
아래는 참고 캡처입니다.

docs: KCP 카드사 다이렉트 경우 카드사 포인트 사용 및 할부 사용 문서 추가

---

src/layouts/ArticleStyle.astro

사파리에서 <details> 못생기게 보이는 문제 수정

---

src/content/docs/ko/console/guide/list.mdx

기술 지원 > 관리자 콘솔 > 결제 내역 에서 `웹훅 재발`으로 오타가 있어 `웹훅 재발송` 으로 수정합니다.

fix: typo (웹훅 재발송)

---

src/layouts/rest-api/category/type-def.tsx
src/layouts/rest-api/schema-utils/type-def.ts

| before | after |
| --- | --- |
| ![image](https://github.com/portone-io/developers.portone.io/assets/690661/74525fa8-8326-45f1-b9f9-5125a477769d) | ![image](https://github.com/portone-io/developers.portone.io/assets/690661/af6dc645-69c5-4f1d-9652-e41d47b0cfb4) |

api 문서에서 format 필드가 있는 속성 문서를 좀 더 친절하게 보여줌

---

src/schema/v2.openapi.json

V2 API 문서에서 본인인증 API 에 대한 타이틀이 누락되어 있어 반영합니다.

V2 본인인증 API Title 추가 

---

src/layouts/rest-api/DescriptionArea.tsx
src/layouts/rest-api/category/type-def.tsx
src/layouts/rest-api/endpoint/EndpointDoc.tsx
src/layouts/rest-api/schema-utils/type-def.ts

| before | after |
| --- | --- |
| ![image](https://github.com/portone-io/developers.portone.io/assets/690661/10c1b49c-10a7-40f0-a585-5230da2aafbf) | ![image](https://github.com/portone-io/developers.portone.io/assets/690661/e1e40e96-9977-45ea-a0d1-d336c517b3d9) |

api 문서의 request, response에 대해서 nested 속성들을 한 단계 보여주도록 함

---

src/pages/docs/[lang]/[...slug].astro

related: https://github.com/portone-io/developers.portone.io/pull/240
context: https://www.notion.so/chaifinance/2024-01-15-2b0052986a1b4a2a8dad813688a28808
`/docs/en`으로 접속하면 됩니다.

구 영문 문서 링크만 알면 들어갈 수는 있도록 함

---

src/layouts/rest-api/category/type-def.tsx

인터넷에서 사용하는 datetime 전송 표준은 RFC 3339이고, 포트원도 ISO 8601의 스펙을 구현하기보다는 RFC 3339를 구현하는 데 가까우므로 설명을 교체합니다.

date-time 설명을 ISO 8601에서 RFC 3339로 교체

---

src/schema/v1.openapi.json

더 이상 사용되지 않는 `x-portone-summary` 를 `x-portone-description`으로 변환하는 작업으로 
최종적으로 해야될 작업은 다음과 같지만 phase2의 경우. 개발자센터에 보여질 UI (대표적으로 개행 ) 와 문장이 적절한지 하나 하나 다 읽어봐야 해서 공수도 크고 무엇보다 리뷰가 매우 오래걸릴 것 같아 두 단계로 나누었고 이 PR은 그 중 phase1에 해당합니다.
- phase1: x-portone-summary 를 전부 x-portone-description으로 옮긴다
- phase2: 두개의 값이 이미 존재하고 서로 다른 경우 맥락을 파악하고 내용을 병합하여 x-portone-description 에 넣는다
상기 사유로 이 PR은 모두 기계적으로 단순 변환 되었으며 그 기준은 다음과 같습니다.
상기 사유로 이 PR은 모두 기계적으로 단순 변환 되었으며 그 기준은 다음과 같습니다. 
- `x-portone-summary` 만 존재할 경우 일괄적으로 `x-portone-description` 으로 치환한다.
- `x-portone-summary`, `x-portone-description` 둘다 존재할 경우
- `x-portone-description` 이 빈문자열일 경우 `x-portone-summary`의 내용을 채우고 `x-portone-summary`는 삭제한다.
- 두개의 내용이 같을 경우 `x-portone-description` 만 남기고 `x-portone-summary`는 삭제한다.
- 두개의 내용이 다를 경우 아무 작업도 하지 않고 그대로 둔다 ( …

docs: x-portone-summary를 x-portone-description 으로 일괄 치환

---

src/state/server-only/nav.ts

동일한 페이지가 네비게이션 메뉴에서 여러번 등장할 경우 (본래는 이런 일이 생길 수 없다고 가정하였으나 v1/v2에서 다른 트리에서 같은 페이지를 바라보는 경우가 생기면서 가정이 깨짐) 자동 메뉴 펼침 동작이 망가지는 문제를 수정하였습니다.

네비게이션 메뉴가 특정 조건에서 잘 안 펼쳐지는 문제 수정

---

src/content/docs/en/result/webhook.mdx
src/content/docs/ko/result/webhook.mdx

웹훅 관련해서 기존에 pay-iamport, api-iamport, paymentadmin 통해서 발송되는 웹훅의 타임아웃에 대해서만 설명이 있었는데, 재발송 경우에 대한 타임아웃에 대한 설명을 추가했습니다.
한글 설명
영문 설명
- [타임아웃 관련 문의](https://portone-io.slack.com/archives/C067FEWAMAQ/p1708065699880509)
- [재발송의 타임아웃 설정 ](https://github.com/iamport/laravel-webhook-sender/blob/c11a8690a8c514d3190bba7e7fb8a3393cf8d975/app/Console/Commands/RetryErrorWebhook.php#L103-L111)
- [guzzle 설정](https://docs.guzzlephp.org/en/stable/request-options.html#timeout)

webhook: add timeout description and remove ip list in en webhook manual

---

src/content/docs/ko/v2-payment/authpay.mdx
src/content/docs/ko/v2-payment/billing-key/1.mdx
src/content/docs/ko/v2-payment/billing-key/2.mdx
src/content/docs/ko/v2-payment/billing-key/3.mdx
src/content/docs/ko/v2-payment/identity-verification.mdx
src/content/docs/ko/v2-payment/key-in.mdx
src/content/docs/ko/v2-payment/pg/ksnet.mdx
src/content/docs/ko/v2-payment/pg/nice-v2.mdx
src/content/docs/ko/v2-payment/pg/tosspayments.mdx
src/content/docs/ko/v2-payment/webhook.mdx
src/pages/api/rest-v2/_Page.tsx

`Authorization: PortOne <API Secret>` 형식의 인증을 사용할 수 있게 됨에 따라, 두 가지 인증 방식을 설명하고, 간편한 새 인증 방식으로 예제 코드를 교체합니다.
V2 Rest API 명세 페이지 상단에 설명이 좀 추가되었고, V2 예제 코드들이 수정되었습니다.

v2: API Secret을 직접 적어 API 인증하는 방식 사용

---

src/state/nav.ts

기존에는 URL의 쿼리 파라미터 혹은 LocalStorage에 임의의 값을 설정 시 해당 값을 사용할 수 있었음

브라우저 내에서 SystemVersion이 v1 혹은 v2이도록 강제

---

src/content/docs/ko/v2-payment/authpay.mdx
src/content/docs/ko/v2-payment/v2.mdx

콘솔 결제연동 페이지가 리뉴얼되면서 V2 API Secret 을 수동으로 발급할 필요가 없어졌습니다.
따라서, V2 Tech Support 메일로 수동발급 요청해야 한다는 부분을 제거하고, 인증 API를 사용하는 최초 페이지인 수기결제 탭에 관련 문구를 추가하였습니다.

결제연동 리뉴얼 - V2 API Secret 수동 발급 문의 부분 제거

---

src/layouts/trackers/GoogleTagManager.astro

This typo renders `)` character in body tag on production deployment.

Fix typo in GTM tracker

---

COPYRIGHT
LICENSE
README.md
package.json

Reference: https://spdx.org/licenses/AGPL-3.0-or-later.html
- [NPM package.json 문서](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license)의 권고사항에 따라 SPDX 식별자 AGPL-3.0-or-later 추가
- LICENSE 파일에 AGPL-3.0 전문 추가
- 명확한 AGPL-3.0-or-later 표현을 위해 COPYRIGHT 파일에 표준 라이센스 헤더 추가

AGPL-3.0-or-later 라이센스 추가

---

package.json
patches/remark-lint-table-cell-padding@4.1.3.patch
pnpm-lock.yaml

remark-lint-table-cell-padding이 전각 문자를 대응하도록 패치

---

src/content/docs/ko/pg/simple/tosspay-v2/readme.mdx
src/content/docs/ko/v2-payment/pg/danal-identity-verification.mdx
src/content/docs/ko/v2-payment/v2-sdk/identity-verification-request.mdx

V2 본인인증과 관련한 수정 사항들을 반영합니다.
- V2 SDK 파라미터 가이드 중 본인인증 요청 시 customer 필드가 optional 이지만 required로 표기되어 있던 부분 수정
- V2 다날 본인인증 연동 가이드에서 다른 페이지로 연결하는 링크 path가 변경되었으나 미반영되어있던 내용 수정
- bypass를 Json.Stringify 하지 않고 직접 사용하는 방식 가이드에도 적용 (토스페이, 다날)
- byass -> bypass 오타 수정

V2 본인인증 가이드 수정사항 적용

---

src/pages/api/rest-v2/_Page.tsx

콘솔에서 V2 API Secret 을 발급받을 수 있게 되면서 관련 내용들을 수정했었는데, 아직 남아있던 부분이 있어서 추가로 수정합니다.

V2 API Secret 콘솔에서 발급받는 방식으로 수정

---

src/content/docs/ko/ready/readme.mdx

[결제 연동 준비하기] 탭에서 V2 API Secret 을 활용하는 방법이 access token 을 발급받는 것으로 한정되어 있던 설명을 변경합니다.
V2 API 페이지로 이동하며 1. 직접 사용 방식, 2. 액세스 토큰 방식인증 방식 중 선택하도록 유도합니다.

V2 API Secret 사용 방식 수정

---

src/content/docs/ko/v2-payment/pg/ksnet.mdx

V2 KSNET 연동가이드 중 productType 필드에 대한 설명이 잘못 기입된 부분이 있어서 수정합니다.

fix: V2 KSNET 가이드 productType 내용 업데이트

---

package.json
pnpm-lock.yaml
src/layouts/rest-api/editor/RequestJsonEditor.tsx
src/layouts/rest-api/endpoint/playground/try/Req.tsx
src/layouts/rest-api/endpoint/playground/try/ReqSample.tsx
src/layouts/rest-api/endpoint/playground/try/ResExample.tsx
src/layouts/rest-api/endpoint/playground/try/Tabs.tsx
src/layouts/rest-api/endpoint/playground/try/Try.tsx
src/layouts/rest-api/schema-utils/operation.ts
src/layouts/rest-api/schema-utils/type-def.ts

- `openapi.json` 스키마에 정의되어 있는 `example` 프로퍼티로 예시 응답을 보여주는 `ResExample` 컴포넌트를 구현했습니다.
- Try 요청 초기값이 `example` 프로퍼티 값으로 설정되도록 했고, `string` 타입의 기본 값을 빈 문자열에서 파라미터 이름으로 변경했습니다.
- `Parameter["type"]`이 `falsy`일 경우에 `Parameter["schema"]["type"]` 값으로 타입이 결정되지 않고 `object`로 잘못 설정되는 버그를 수정했습니다.
- [httpsnippet-lite](https://github.com/P0lip/httpsnippet) 라이브러리를 사용해서 Try 요청을 다양한 코드 샘플로 보여주는 `ReqSample` 컴포넌트를 구현했습니다.
- Try 응답 결과를 보여주는 컴포넌트를 기본적으로 비활성화 하고, 요청을 실행했을 때 표시하도록 변경했습니다.
- Example 섹션을 별도로 만들기 보다는, 기존에 사용하고 있던 Try 섹션에서 예시 파라미터 값을 보여주는 방향이 공간 효율적이고, 에디터로 수정할 수 있으면서 복사도 용이하기 때문에 DX면에서 더 좋다고 판단했습니다.
- 응답 결과를 보여주는 컴포넌트를 기본적으로 비활성화 한 이유는, 이렇게 하면 요청 에디터와 요청 샘플을 나란히 표시할 수 있고, 응답 결과 자체가 사용자가 실행 버튼을 누르는 Action이 있어야 생성되는 데이터이기 때문에 굳이 N/A 형태로 표시할 이유가 없다고 판단했기 때문입니다.
- `string` 타입의 기본값을 파라미터 이름으로 설정한 이유는 요청 …

개발자센터 api 문서 예시 요청/응답 값 보여주기

---

src/components/gitbook/VersionGate.astro
src/components/gitbook/VersionGate.tsx
src/layouts/gnb/Dropdown.tsx
src/layouts/gnb/Gnb.astro
src/layouts/gnb/VersionSwitch.tsx
src/layouts/sidebar/DocsNavMenu.astro
src/layouts/sidebar/LeftSidebarItem.tsx
src/layouts/sidebar/search.tsx
src/state/nav.ts
src/state/server-only/nav.ts
src/type.ts

일단 패스
---
Concern points:
- 세션 스토리지 활용하는 대신에 쿠키에다가 버전 정보를 박아서 URL에 `?v=`를 인코딩하기 위해 여기저기 깊게 `serverSystemVersion`을 침투시킬 필요가 없이 할 수도 있을 것 같은데 이걸 이번 iteration에 구현할지
- 지금 구현상 서버 내 프레임워크 컴포넌트(Preact)에 대해서는 프롭드릴링을 하도록 되어 있는데 `AsyncLocalStorage` 같은 거 사용할 방법 없을지....?

서버에서 URL로 V1/V2 구분 가능하도록 개선

---

src/components/gitbook/Details.astro

closes #352 
Link: https://developers-8qtiz9ivg-portone.vercel.app/docs/ko/v2-payment/pg/paypal-v2?v=v2#%EC%A0%95%EA%B8%B0%EA%B2%B0%EC%A0%9C-%EC%9C%A0%EC%9D%98%EC%82%AC%ED%95%AD

<Details> 내부 레이아웃을 flex에서 grid로 변경

---

src/layouts/rest-api/editor/RequestJsonEditor.tsx
src/layouts/rest-api/endpoint/EndpointDoc.tsx
src/layouts/rest-api/endpoint/playground/try/Req.tsx
src/layouts/rest-api/endpoint/playground/try/ReqSample.tsx
src/layouts/rest-api/endpoint/playground/try/Try.tsx
src/layouts/rest-api/misc/SchemaDownloadButton.tsx
src/layouts/rest-api/schema-utils/operation.ts
src/layouts/rest-api/schema-utils/type-def.ts
src/pages/api/rest-v1/_Page.tsx
src/pages/api/rest-v2/_Page.tsx
src/pages/api/schema/[version].openapi.json.ts

closes #427 
- Astro endpoint 기능으로 트랜스폼된 api 스키마를 다운로드 받을 수 있는 정적 링크 구현
- Operation 내에 `x-portone-query-or-body` 속성의 Parameter가 있으면 언어 / 라이브러리에 따라 Body 객체를 `requestBody` 쿼리로 보내거나 GET with Body로 보내도록 구현
- API 엔드포인트 문서에 `requestBody` 관련 설명 추가

`x-portone-query-or-body` 대응

---

package.json

closes #460 
ts-node 도입 이후, 기존 `pnpm eslint` 명령어를 사용하려면 수동으로 `NODE_OPTIONS` 환경변수를 설정해야 하는 문제가 있어 이를 해결하기 위해 package.json에 `eslint` 스크립트를 구현하는 PR입니다.

eslint 스크립트 추가

---

src/layouts/sidebar/DocsNavMenu.astro
src/layouts/sidebar/LeftSidebarItem.tsx
src/state/server-only/nav.ts
src/type.ts

이런 식으로 쓸 수 있습니다
이렇게 생겼습니다
누르면 새 탭에서 열립니다

좌측 내비게이션에 외부 링크 기능 구현

---

packages/lint-local-links-valid/src/remark.ts
src/content/docs/en/api/api/readme.mdx
src/content/docs/en/api/billing-key-api/readme.mdx
src/content/docs/en/api/escrow-api/readme.mdx
src/content/docs/en/api/subscription-payment-api/readme.mdx
src/content/docs/en/auth/guide-1/bill/readme.mdx
src/content/docs/en/auth/guide/4/readme.mdx
src/content/docs/en/ready/2-pg/payment-gateway-settings/readme.mdx
src/content/docs/ko/pg/simple/readme.mdx
src/content/docs/ko/wordpress/wordpress/readme.mdx
src/content/docs/ko/wordpress/wordpress/woocommerce/readme.mdx

closes #458 
- <ContentRef> 컴포넌트의 slug 링크를 검사하는 remark lint 규칙을 추가했습니다.
- 린터에서 감지된 유실된 링크 37개를 수정했습니다.

<ContentRef> 링크 검사하는 lint 규칙 추가

---

src/content/docs/en/payment-integration-by-pg/payment-gateways/inicis.mdx
src/content/docs/ko/pg/payment-gateway/inicis.mdx

- 한국어/영문 가이드에 모두 추가
- 한국어 가이드에 있지만 영문 가이드에 없던 내용 추가
- 한국어 가이드에서 스타일 깨지던 부분 수정
- 한국어 가이드에서도 영문 가이드처럼 Details 컴포넌트 사용해서 결제수단 구분코드 접어두게 함

payment-gateway/inicis.mdx: iOS에서 계좌이체시 결제가 이뤄지던 앱으로 돌아가기 설정 설명 추가

---

src/content/docs/en/tips/pg-codes.mdx
src/content/docs/ko/api-v2/billing-key.mdx
src/content/docs/ko/api-v2/cash-receipt.mdx
src/content/docs/ko/api-v2/payment.mdx

- https://github.com/portone-io/browser-sdk/pull/299
https://portone-io.slack.com/archives/C050NUE2C30/p1715830075923449

더이상 지원하지 않는 PG사(syrup, kakao, payple) 목록 삭제

---

src/content/docs/ko/v2-payment/v2-sdk/_components/SDKChangelog.astro

변경사항 내에 rich text가 포함되어 있으면 text node가 나뉘어져서 정규식 매칭이 안됐었음

SDK 체인지로그에서 커밋 해시 제거하는 로직 내 버그 수정

---

src/content/docs/ko/pg/payment-gateway/daou/undefined.mdx

docs: 다우데이타 유의사항 추가
비인증 결제 API 호출 횟수가 초당 50건을 초과할 경우 오류가 발생할 수 있어 해당 내용을 추가했습니다.

docs: 다우데이타 유의사항 추가

---

src/layouts/rest-api/endpoint/playground/try/Req.tsx

Slack 링크: https://portone-io.slack.com/archives/C03N8773P1A/p1718609124285429?thread_ts=1718608700.086539&cid=C03N8773P1A
대소문자 구분 때문에 CORS 정책으로 차단되는 문제 해결 😢

fetch method 대소문자 이슈 수정

---

src/schema/v1.openapi.json

V1 openApi 스키마를 업데이트 했습니다.
- cmd:
```
deno run -A ./scripts/download-schema.ts
```
- 예약결제 등록 시 요청 파라미터 name을 required로 변경(하위 호환을 위해 실제론 optional 동작을 유지함, [참고](https://github.com/portone-io/api-iamport/pull/722/files))
- 표현 변경: 가맹점 => 고객사ㅑ
- 그 외 등등

update V1 openapi schema

---

src/routes/(root)/docs.tsx

[Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)로 인해 solid에서 변경사항을 트래킹할 수 없었던 것이 원인이었습니다.
읽어볼만한 글: https://github.com/solidjs/solid/discussions/1708#discussioncomment-5774328

문서의 title과 description이 변경되지 않는 버그 수정

---

src/routes/(root)/docs/en/_nav.yaml
src/routes/(root)/docs/en/etc/budget.mdx
src/routes/(root)/docs/en/readme.mdx
src/routes/(root)/docs/ko/_nav.yaml
src/routes/(root)/docs/ko/etc/budget.mdx
src/routes/(root)/docs/ko/readme/index.mdx

Gitbook 링크 걸려있던 메뉴 삭제. 해당 가이드는 현재 크림만 쓰기 때문에 크림 요청 시 기존 깃북 주소 전달

버짓핸들러 기존 메뉴삭제

---

src/routes/(root)/api/rest-v1/[...slug].tsx
src/routes/(root)/docs/ko/readme/index.mdx

Legacy cipher 지원 중단에 대한 안내를 2024년 3월부터 메일로 보내왔으나 신규 가맹점들에 한해서는 legacy cipher를 사용하는 가맹점을 막을 수 없는 문제가 있습니다.
이에 따라 개발자센터에도 지원 중단 관련된 문구를 노출합니다.
- 메인 페이지
- API 개요 페이지

메인 페이지에 Legacy cipher 지원 중단 Hint 추가

---

src/components/gitbook/File.tsx

[Slack 논의](https://portone-io.slack.com/archives/C067FEWAMAQ/p1722835850481659)
- target="_blank" 적용
- filename을 optional로 만들고, 기본값으로 다운로드 경로의 파일 이름을 사용

File 컴포넌트 404 오류 해결

---

src/layouts/sidebar/search.tsx

- `/index` 로 끝나는 slug에 대한 처리 추가
```ts
.map((item) => {
const slug = item.slug.replace(/\/index$/, "");
return { ...item, slug };
})
```

검색 시 index 문서가 잘못된 링크를 생성하지 않도록 수정

---

src/routes/(root)/opi/ko/readme/index.mdx

- 콘솔 가이드로 향하는 링크가 잘못되어 있어 수정합니다.
- 기존에 api 문서 링크를 달아주기 위해 `ContentRef` 를 사용했었는데, `ContentRef`는 opi 하위의 mdx 문서들에 대해서만 사용할 수 있는 컴포넌트여서 api 문서에 대해서는 A 태그를 직접 이용해 링크를 만들어주도록 변경했습니다.

readme 페이지의 일부 링크 수정

---

package.json
pnpm-lock.yaml
scripts/calc-api-redir.ts
scripts/download-schema.ts
scripts/nav-labels.ts
src/layouts/rest-api/category/type-def.tsx
src/layouts/rest-api/endpoint/EndpointDoc.tsx
src/misc/md.ts
src/schema/v2.openapi.json

OpenAPI 표준에서는 description 필드에 HTML을 허용하지 않고, CommonMark를 허용하고 있습니다. 스키마 JSON 파일에서 설명을 HTML로 변환하지 않고 그대로 사용하되, 필요한 경우 HTML로 변환하도록 수정했습니다.
- `-`로 시작하는 일부 설명이 markdown 문법으로 처리되고 있는 부분의 문서 수정이 필요합니다.

v2 openapi 스키마에서 markdown을 그대로 사용하도록 수정

---

src/routes/(root)/opi/ko/integration/start/v2/checkout.mdx

문서에 기재된 'payment_Id'가 아닌 카멜표기 'paymentId'로 전달되는 것으로 확인. 다른사람들은 연동에 시간이 낭비되지 않았으면함.

fix: paymentId 오표기

---

src/layouts/sidebar/RightSidebar.tsx
src/routes/(root)/platform/(doc).tsx

- 문서를 이동해도 제목과 ToC 내용이 변경되지 않는 버그 수정
- `이 페이지 수정하기` 버튼 클릭 시 잘못된 링크로 이동하는 버그 수정

파트너정산 자동화 문서 버그 수정

---

src/routes/(root)/opi/ko/_nav.yaml
src/routes/(root)/opi/ko/integration/v2-mobile-sdk/readme.mdx

모바일 SDK 목차를 추가하고, android v2 sdk 내용을 추가했습니다. 사용법 관련해서는 android sdk 레포 readme에 정리해두어 개발자센터에는 작성하지 않았는데, 너무 허전해보여서 추가로 설치방법이나 사용 방법 기술할지 한번 확인 부탁드립니다.

모바일 SDK 목차 추가, android v2 sdk 내용 추가

---

src/routes/(root)/opi/ko/integration/webhook/readme-v2.mdx

고객사에서 웹훅 연동 관련 문의가 많이 접수되고 있어, 최신 서버 sdk를 활용한 샘플 코드를 기반으로 예시 코드를 재작성했습니다.

웹훅 예시 코드가 서버 sdk를 활용한 샘플 프로젝트에 기반하도록 변경

---

src/layouts/gnb/Gnb.tsx
src/routes/(root)/sdk/ko/_nav.yaml
src/routes/(root)/sdk/ko/readme/index.mdx

- Client SDKs -> 모바일 SDK
- Server SDKs -> 서버 SDK
- JS SDK -> 브라우저 SDK
JS SDK는 상단 메뉴 링크와 SDK 문서 title만 변경하고 문서 내 표현은 유지했습니다.

SDK 메뉴 명칭 변경 & 브라우저 SDK 링크 추가

---

src/routes/(root)/sdk/ko/v2-server-sdk/readme.mdx

기존에 구버전 혹은 x.x.x로 안내되던 버전 대신 뱃지로 갈음합니다.

서버 SDK 버전 뱃지 추가

---

src/routes/(root)/opi/ko/extra/identity-verification/readme-v2.mdx
src/routes/(root)/opi/ko/integration/start/v1/auth.mdx
src/routes/(root)/opi/ko/integration/start/v2/billing/issue.mdx
src/routes/(root)/opi/ko/integration/start/v2/checkout.mdx
src/routes/(root)/sdk/ko/v2-sdk/billing-key-response.mdx
src/routes/(root)/sdk/ko/v2-sdk/identity-verification-response.mdx
src/routes/(root)/sdk/ko/v2-sdk/payment-response.mdx

* 빌링키 응답 관련 필드 오류 수정
* pgCode, pgMessage 필드 추가
* `!= null` 비교가 undefined를 포함하는데, 이 점을 알지 못하고 `!== null`로 비교하여 오류 발생하는 경우가 있음. undefined로 응답하는 것이 고정되어 있으므로 `!== undefined`로 비교하도록 함

SDK 응답 설명 최신화

---

src/routes/(root)/opi/ko/integration/pg/v1/ksnet/readme.mdx
src/routes/(root)/opi/ko/integration/pg/v1/naver.mdx
src/routes/(root)/opi/ko/integration/start/v1/auth.mdx
src/routes/(root)/sdk/ko/v1-sdk/javascript-sdk/payrq.mdx

- v1 네이버페이 결제형 연동문서에 헬프센터 검수요청 가이드 링크 추가
- v1 인증결제 연동 예시 코드 중 잘못된 코드 수정
- v1 SDK > 결제요청 파라미터와 v1 KSNET 연동 가이드에 상점 부담 무이자 할부에 대한 설정 방법과 그와 관련된 파라미터 설명 추가

v1 가이드 설명 보완 및 잘못된 연동 예시 코드 수정

---

src/routes/(root)/api/rest-v1/[...slug].tsx

해당 강제개행 되는 문제를 해결합니다.
https://github.com/portone-io/developers.portone.io/blob/main/src/routes/(root)/opi/ko/readme/index.mdx?plain=1 해당 파일에서 Hint 컴포넌트를 복사했습니다.

:memo: docs(rest-v1): 보안규격 지원 종료안내 강제 개행 수정

---

src/components/interactive-docs/CodePanel.tsx
src/layouts/docs/InteractiveDocs.tsx
uno.config.ts

사이즈가 일그러지는 버그를 수정했습니당
|AS-IS|TO-BE|
|-----|-----|
|<img width="768" alt="image" src="https://github.com/user-attachments/assets/165bf8fe-4c37-4398-a748-2db265372350" />|![image](https://github.com/user-attachments/assets/a8935cf2-7a41-48c3-86dc-3ea341cae32b)|

fix(layout): v2 퀵가이드에서 사이즈가 줄어들경우 래이아웃이 찌그러지는 버그 수정

---

.npmrc

- post install 스크립트가 제거되어서 더 이상 사용하지 않는 옵션임

`side-effects-cache` 재활성화

---

src/routes/(root)/opi/ko/quick-guide/payment/index.mdx

스마트로 퀵 가이드 내용 추가

---

src/routes/(root)/api/rest-v1/[...slug].tsx

[V1 API 개요](https://developers.portone.io/api/rest-v1?v=v1)란에 아래와 같이 하위 상점 이용 시 티어코드 전달이 필요함을 표시 했습니다.

[v1/api] 포트원 API 하위상점 사용 시 유의사항 추가

---

src/layouts/rest-api/schema-utils/type-def.ts

https://developers.portone.io/api/rest-v1/type-def?v=v1#PaymentAnnotation
타입 정의 섹션에서 PaymentAnnotation을 펼치면 페이지가 터지는 버그를 고쳣습니다

fix: api/rest-v1/type-def?v=v1#PaymentAnnotation 에서 PaymentAnnotation을 클릭시 페이지가 터지는 버그 수정

---

scripts/docs-for-llms/generator.ts
scripts/llms-txt/generator.ts
scripts/mdx-to-markdown/README.md
scripts/mdx-to-markdown/index.ts
scripts/mdx-to-markdown/jsx/a.test.ts
scripts/mdx-to-markdown/jsx/a.ts
scripts/mdx-to-markdown/jsx/common.ts
scripts/mdx-to-markdown/jsx/file.test.ts
scripts/mdx-to-markdown/jsx/file.ts
scripts/mdx-to-markdown/jsx/img.test.ts
scripts/mdx-to-markdown/jsx/img.ts
scripts/mdx-to-markdown/jsx/importedMdx.test.ts
scripts/mdx-to-markdown/jsx/importedMdx.ts
scripts/mdx-to-markdown/jsx/imports.ts
scripts/mdx-to-markdown/jsx/index.test.ts
scripts/mdx-to-markdown/jsx/index.ts
scripts/mdx-to-markdown/jsx/parameter.test.ts
scripts/mdx-to-markdown/jsx/parameter.ts
scripts/mdx-to-markdown/jsx/sdk.test.ts
scripts/mdx-to-markdown/jsx/sdk.ts
scripts/mdx-to-markdown/mdx-parser.ts

- `Parameter.TypeDef`, `SDKChangelog`, `SDKParameter`, `img`, `A`, `File` 등 미지원 JSX 태그들에 대한 마크다운 변환을 추가했습니다.
- 기타 html tag들에 대해서는 마크다운 내에서도 그대로 유지되도록 개선했습니다.
- import statement를 통해 임베딩되는 mdx 문서들이 마크다운 변환 시에도 문서 내에 첨부되도록 개선했습니다.
위 변경사항은 `llms-txt` `docs-for-llms` 스크립트에 반영됩니다.

마크다운 변환 추가 지원

---

scripts/docs-for-llms/README.md
scripts/docs-for-llms/generator.ts
scripts/docs-for-llms/index.ts
scripts/llms-txt/README.md
scripts/llms-txt/generator.ts
scripts/llms-txt/index.ts
scripts/mdx-to-markdown/utils.ts

`pnpm llms-txt`, `pnpm docs-for-llms`에 존재하는 공통 로직 중 `scripts/mdx-to-markdown`에 포함될 수 있는 것들을 `scripts/mdx-to-markdown/utils.ts`로 옮겨 리팩토링했습니다.

`llms-txt`, `docs-for-llms` 스크립트 리팩토링

---

scripts/llms-txt/generator.ts
scripts/mdx-to-markdown/index.ts

`llms-small.txt` 의 기존 내용 이후에 각 문서별 프론트매터가 아래와 같은 형식으로 추가됩니다.

`llms-small.txt`에 문서별 프론트매터 추가

---

.gitignore
package.json
scripts/docs-for-llms/README.md
scripts/docs-for-llms/generator.ts
scripts/guide-for-llms.md
scripts/mdx-to-markdown/jsx/importedMdx.ts
src/routes/(root)/_components/ko/docs-for-llms.mdx
src/routes/(root)/_components/ko/llms-txt-support.mdx
src/routes/(root)/_components/ko/using-mcp-server.mdx
src/routes/(root)/opi/ko/_nav.yaml
src/routes/(root)/opi/ko/integration/using-ai-tools.mdx
src/routes/(root)/platform/ko/_nav.yaml
src/routes/(root)/platform/ko/using-ai-tools.mdx

- 원 페이먼트 인프라, 파트너정산 탭에 각각 `AI 도구 활용하기` 항목을 추가했습니다.
- 해당 문서는 llms.txt, portone-mcp-server, docs-for-llms 관련 내용을 담고 있습니다.
- `pnpm docs-for-llms` 실행 시 `public/docs-for-llms.zip`을 생성하도록 변경하고, `pnpm build` 시 자동으로 실행되도록 변경했습니다.

`AI 도구 활용하기` 문서 추가

---

src/routes/(root)/opi/ko/quick-guide/payment/_preview/type.test.ts
src/routes/(root)/opi/ko/quick-guide/payment/_preview/type.ts
src/routes/(root)/opi/ko/quick-guide/payment/_preview/utils.ts
src/routes/(root)/opi/ko/quick-guide/payment/backend-code.ts
src/routes/(root)/opi/ko/quick-guide/payment/frontend-code.ts

`GET /opi/ko/quick-guide/payment/backend-code` `GET /opi/ko/quick-guide/payment/frontend-code`를 추가합니다.
해당 API는 https://github.com/portone-io/mcp-server 에서 활용하기 위한 용도로, pg, payMethod, framework에 따라 샘플 코드를 마크다운 형식으로 반환합니다.

퀵 가이드 샘플 코드를 반환하는 GET API 추가

---

src/routes/(root)/_components/ko/llms-txt-support.mdx

llms.txt 가 solidjs/router에 포함되어있지 않아 저 링크를 누르면 404가 뜹니다. 새로고침을 하면 정상적으로 로딩이 되는데, 라우터가 저 파일들을 인식하는게 아주 자명하진 않아서 그냥 애초에 파일을 새 탭에서 켜게 만들었습니다.

llms-txt-support.mdx: Open llms.txt in a new tab

---

src/routes/(root)/sdk/ko/v1-sdk/javascript-sdk/payrt.mdx

name 필드 설명과 buyer_name 필드 설명이 중복됩니다.
name을 주문상품명으로 변경했습니다.
현재 결제응답 파라미터 페이지의 필드 설명입니다.
https://developers.portone.io/sdk/ko/v1-sdk/javascript-sdk/payrq?v=v1

name 필드 설명란에 주문자명에서 주문상품명으로 변경

---

scripts/mdx-to-markdown/utils.ts

- `fastGlob`로 파일 목록을 가져올 때 매 번 순서가 변하는 문제를 수정합니다.
- `llms.txt` `website-links.md` 등 `pnpm llms-txt` `pnpm docs-for-llms`에서 생성되는 문서 목록이 항상 정렬되어 동일한 결과를 내도록 수정합니다.

LLM 전용 문서 목록이 항상 정렬되어 출력되도록 개선

---

src/routes/(root)/opi/ko/integration/pg/v1/nhn-kcp.mdx
src/routes/(root)/opi/ko/integration/pg/v1/settle/mybank.mdx

v1 헥토, 퀵페이에서 ci 값을 평문이 아닌 암호화된 값으로 전달하도록 문서 수정했습니다.

[v1] KCP퀵페이, 헥토파이낸셜 결제 연동 파라미터 수정

---

packages/browser-sdk-mdx-codegen/src/parameter.ts
packages/browser-sdk-mdx-codegen/src/schema.ts
packages/browser-sdk-mdx-codegen/src/utils.ts
src/components/parameter/Parameter.tsx

https://github.com/portone-io/browser-sdk-generator/pull/2 로 바뀔 예정인 스키마에서 parameterRef 타입의 멤버를 가진 discriminatedUnion이 각 discriminator의 값에 따라 달라진다는 주석을 표시하지 못 하고 있어서 해당 부분을 수정했습니다.

`Parameter.TypeDef` 에 leadingDescription 구현

---

src/routes/(root)/opi/ko/_nav.yaml
src/routes/(root)/opi/ko/integration/pg/v1/kcp-v2-identity-verification.mdx
src/routes/(root)/opi/ko/integration/pg/v2/kcp-v2-identity-verification.mdx

kcp 연동 가이드 추가 pr(https://github.com/portone-io/developers.portone.io/pull/848) 에서 경로추가가 누락되어 추가하였습니다.

nav.yaml에 kcp 본인인증 경로추가

---

src/routes/(root)/opi/ko/integration/pg/v1/eximbay.mdx

엑심베이에서 지원하지 않는 통화코드가 결제 가능한 것으로 잘못 안내하고 있어
지원하지 않는 결제 통화는 제거합니다

chore: v1 eximbay 지원하지 않는 통화 제거

---

src/routes/(root)/opi/ko/integration/pg/v1/kakaopay.mdx

카카오페이 결제, 결제 취소 시 부가세 지정이 불가능함을 안내하는 내용 추가합니다.

docs:v1 카카오페이 부가세 지정 미지원 설명 유의사항 추가

---

src/routes/(root)/opi/ko/extra/identity-verification/v1/all/3.mdx
src/routes/(root)/opi/ko/extra/identity-verification/v1/credit-auth/4.mdx
src/routes/(root)/opi/ko/extra/identity-verification/v1/phone/4.mdx

포트원 V1 본인인증 내역 조회 API의 응답에서 생년월일 필드명은 birthday입니다.
연동가이드에서 birth로 잘못 작성되어 있어 birthday로 수정합니다.

docs:v1 본인인증 결과처리 가이드에서 생년월일 필드명이 잘못되어 수정합니다.
